<?php

/**
 * @file
 * Contains github_api_example.module..
 */

use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 *
 * Add a 'GitHub username' base field to user entity.
 *
 * {@inheritdoc}
 */
function github_api_example_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  $fields = array();
  if ($entity_type->id() === 'user') {
    $fields['github_username'] = $storage_definition = BaseFieldDefinition::create('string')
      ->setLabel(t('GitHub username'))
      ->setDescription(t('GitHub username.'))
      ->setTranslatable(FALSE)
      ->setRevisionable(TRUE)
      ->setSetting('max_length', 255)
      ->setDisplayOptions('view', array(
        'label' => 'hidden',
        'type' => 'string',
        'weight' => -5,
      ))
      ->setDisplayOptions('form', array(
        'type' => 'string_textfield',
        'weight' => -5,
      ))
      ->setDisplayConfigurable('form', TRUE);
  }

  return $fields;
}

/**
 * Implements hook_theme().
 */
function github_api_example_theme() {
  return [
    'github_info' => [
      'variables' => [
        'account' => NULL,
        'repositories' => NULL,
        'organisations' => NULL
      ],
    ],
  ];
}